name: Docker Compose Test

on:
  repository_dispatch:
    types: [submodule-update]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml run --rm your-test-service